# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  trivyVersion: 0.9.1

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dileep-dockerhub-azure-pipeline'
        repository: 'dileeps9/image-set-using-auzrePipelines'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Install_trivy
  jobs:
    - job: installing_trivy
      steps:
      - script: |
          sudo apt-get install rpm
          wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
          sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
          trivy -v
        displayName: Trivy downloading 


- stage: Scan
  jobs:
    - job: scan_using_trivy
      steps:

      - task: CmdLine@2
        displayName: Scan
        inputs:
          script: |
            sudo trivy image dileeps9/image-set-using-auzrepipelines:$(tag)
            
