# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dileep-dockerhub-azure-pipeline'
        repository: 'dileeps9/image-set-using-auzrePipelines'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Scan
  jobs:
    - job: scan_using_trivy
      steps:

      - task: CmdLine@2
        displayName: Scan
        inputs:
          script: |
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH --ignore-unfixed dileep-dockerhub-azure-pipeline/dileeps9/image-set-using-auzrePipelines:$(tag)
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --severity CRITICAL --ignore-unfixed dileep-dockerhub-azure-pipeline/dileeps9/image-set-using-auzrePipelines:$(tag)
